### ISSUE TITLE
XChat wrongly reported as 'not installed'

### ISSUE THREAD

**Issue by igor-cali** [sebikul/mundus#2]
System:
- Ubuntu 14.04 LTS (trusty) with package
- Mundus package <code>3.0.1-ppa0~ubuntu14.04.1</code> installed
- debian package <code>xchat</code> NOT installed
- debian package <code>xchat-gnome</code> installed.

I think xchat-gnome uses same configuration folder as xchat (<code>~/.xchat2</code>).
Then, if xchat-gnome is installed Mundus should report the application is installed.

**Comment by sebikul** [comment]
Thanks for the report, and sorry for the delay!

I've fixed it in commit 1a6cc838d1656608680aacba4e734d026e439db5. If you can install Mundus from source, please confirm the fix. I will push an update in the following days.

Thanks again!

**Comment by igor-cali** [comment]
Ciao Sebastian,

The commit below works if compiled from source. Thanks! I'll be waiting
for the Ubuntu update.

You could improve the makefile to post a message if Gambas compiler is
not installed (I hadn't it and I had to check the wiki to have some clue).
If you think about adding support for translations to the project, I
could offer myself to help with Italian.

Regards,

igor

Il 18/02/2016 03:14, Sebastian Kulesz ha scritto:

**Comment by sebikul** [comment]
The update should be live. I will try to work on the makefile for the next release. Ideally, a configure script should be included to search for the Gambas compiler. I am actually hoping to move the project to cmake, which should do this automatically.

Regarding the translations, all you need to do is download the source code, and open the Mundus project using the Gambas IDE (You will need to install the IDE, which you can do following [this instructions](http://gambaswiki.org/wiki/install/ubuntu)). You will be given the option to translate all available strings. You can read more about [translating a Gambas project here](http://gambaswiki.org/wiki/howto/translate). If you need any further help you can contact me directly, or create a fork and a pull request so that we can have this discussion there.

Thanks again!
